version: '3'
services:
  test:
    build:
      context: test
      dockerfile: Dockerfile
    volumes:
      - .:/sys-sage
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        cmake -S /sys-sage -B /sys-sage-build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug -DPROC_CPUINFO=ON -DDS_HWLOC=ON -DDS_NUMA=ON -DPAPI=ON
        cmake --build /sys-sage-build --parallel
        sudo cmake --install /sys-sage-build --prefix /usr
        cmake -S /sys-sage/test -B /test-build -DCMAKE_BUILD_TYPE=Debug
        cmake --build /test-build
        /test-build/test
        python3 -m venv /venv
        /venv/bin/python -m pip install /sys-sage/python
        /venv/bin/python /sys-sage/test/topology.py
        /venv/bin/python /sys-sage/test/relation.py
        /venv/bin/python /sys-sage/test/datapath.py
