version: '3'
services:
  test:
    build:
      context: test
      dockerfile: Dockerfile
    volumes:
      - .:/sys-sage
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        cmake -S /sys-sage -B /build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/inst-dir -DPY_SYS_SAGE=ON -DTEST=ON -GNinja
        cmake --build build --target all install test
        ./build/test/test
        PYTHONPATH=$(echo /inst-dir/lib/python*/site-packages) python3 /sys-sage/test/topology.py
        PYTHONPATH=$(echo /inst-dir/lib/python*/site-packages) python3 /sys-sage/test/datapath.py
        PYTHONPATH=$(echo /inst-dir/lib/python*/site-packages) python3 /sys-sage/test/relation.py
