link_libraries(sys-sage sys-sage)
include_directories(../src)
# include_directories(../src/external_interfaces)
# include_directories(../src/pa)

######################################################
################## GENERAL EXAMPLES ##################
######################################################

add_executable(basic_usage basic_usage.cpp)
target_link_libraries(basic_usage PRIVATE sys-sage)

add_executable(custom_attributes custom_attributes.cpp)
target_link_libraries(custom_attributes PRIVATE sys-sage)

add_executable(mt4g-parser mt4g-parser.cpp)
target_link_libraries(mt4g-parser PRIVATE sys-sage)

add_executable(larger_topo larger_topo.cpp)
target_link_libraries(larger_topo PRIVATE sys-sage)

add_executable(sys-sage-benchmarking sys-sage-benchmarking.cpp)
target_link_libraries(sys-sage-benchmarking PRIVATE sys-sage)

add_executable(use_custom_parser custom_parser_musa/use_custom_parser.cpp custom_parser_musa/musa_parser.cpp custom_parser_musa/musa_parser.hpp)
target_link_libraries(use_custom_parser PRIVATE sys-sage)

add_executable(cccbenchplushwloc cccbenchplushwloc.cpp)
target_link_libraries(cccbenchplushwloc PRIVATE sys-sage)

add_executable(iqm-test iqm-test.cpp)
target_link_libraries(iqm-test PRIVATE sys-sage)

add_executable(xml_import xml_import.cpp)
target_link_libraries(xml_import PRIVATE sys-sage)

######################################################
############ BUILD-OPTION-SPECIFIC EXAMPLES ##########
######################################################

if(INTEL_PQOS)
    add_executable(matmul matmul.cpp)
    target_compile_options(matmul PRIVATE -O3)
    target_link_libraries(matmul PRIVATE
        sys-sage
        hwloc
        pqos
    )
endif()

if(NVIDIA_MIG)
    add_executable(nvidia-mig nvidia-mig.cpp)
    target_link_libraries(nvidia-mig PRIVATE sys-sage)
endif()

if(PROC_CPUINFO)
    add_executable(cpu-frequency cpu-frequency.cpp)
    target_link_libraries(cpu-frequency PRIVATE sys-sage)
endif()

if(PAPI)
    add_executable(papi_basics papi_basics.cpp)
    target_link_libraries(papi_basics PRIVATE sys-sage)

    add_executable(papi_multithreading papi_multithreading.cpp)
    target_link_libraries(papi_multithreading PRIVATE sys-sage)

    add_executable(papi_monitor_process papi_monitor_process.cpp)
    target_link_libraries(papi_monitor_process PRIVATE sys-sage)

    add_executable(papi_migrate_cpus papi_migrate_cpus.cpp)
    target_link_libraries(papi_migrate_cpus PRIVATE sys-sage)
endif()

if(PAPI AND PROC_CPUINFO)
    add_executable(papi_greenscore papi_greenscore.cpp)
    target_link_libraries(papi_greenscore PRIVATE sys-sage)
endif()

if(QDMI)
    add_executable(qdmi-test qdmi-test.cpp)
    target_link_libraries(qdmi-test PRIVATE
        sys-sage
        qdmi
        qinfo
    )
endif()

######################################################
#################### INSTALLATION ####################
######################################################

include(GNUInstallDirs)

install(TARGETS basic_usage mt4g-parser custom_attributes larger_topo sys-sage-benchmarking use_custom_parser cccbenchplushwloc xml_import iqm-test DESTINATION ${CMAKE_INSTALL_BINDIR}/examples)
install(DIRECTORY example_data DESTINATION ${CMAKE_INSTALL_BINDIR}/examples)
