on:
  workflow_call:
    inputs:
      flags:
        type: string
        default: ''
jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get build tools
        run: sudo apt-get install -yy g++ cmake ninja-build git
      - name: Get dependecies
        run: sudo apt-get install -yy libxml2-dev nlohmann-json3-dev python3 pybind11-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=inst-dir -DPY_SYS_SAGE=ON -DTEST=ON -GNinja ${{ inputs.flags }}
      - name: Build
        run: cmake --build build --target all install test
      - name: Cpp tests
        run: ./build/test/test
      - name: Python tests
        run:  PYTHONPATH=./inst-dir/lib/python3.13/site-packages/ python3 test/topology.py; \
              PYTHONPATH=./inst-dir/lib/python3.13/site-packages/ python3 test/datapath.py; \
              PYTHONPATH=./inst-dir/lib/python3.13/site-packages/ python3 test/relation.py